2020-10-09 15:29:36,664 ERROR: Exception on /admin/ [GET] [in c:\users\sergio\desktop\project\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\base.py", line 452, in index
    return self.render(self._template)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\base.py", line 308, in render
    return render_template(template, **kwargs)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Sergio\Desktop\heroku deploy\Team-668\app\templates\admin\index.html", line 1, in top-level template code
    {% extends 'admin/master.html' %}
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\templates\bootstrap2\admin\master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\templates\bootstrap2\admin\base.html", line 35, in top-level template code
    {% block page_body %}
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\templates\bootstrap2\admin\base.html", line 42, in block "page_body"
    {% block main_menu %}
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\templates\bootstrap2\admin\base.html", line 44, in block "main_menu"
    {{ layout.menu() }}
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\jinja2\runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\templates\bootstrap2\admin\layout.html", line 55, in template
    {%- if item.is_accessible() and item.is_visible() -%}
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\menu.py", line 126, in is_accessible
    return self._view.is_accessible()
  File "C:\Users\Sergio\Desktop\heroku deploy\Team-668\app\models.py", line 378, in is_accessible
    admin = User.query.get_or_404(email=current_app.config["ADMIN_MAIL"])
TypeError: get_or_404() got an unexpected keyword argument 'email'
2020-10-09 15:31:12,894 INFO: HomeShop startup [in C:\Users\Sergio\Desktop\heroku deploy\Team-668\app\__init__.py:110]
2020-10-09 15:31:18,060 ERROR: Exception on /admin/ [GET] [in c:\users\sergio\desktop\project\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\base.py", line 452, in index
    return self.render(self._template)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\base.py", line 308, in render
    return render_template(template, **kwargs)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Sergio\Desktop\heroku deploy\Team-668\app\templates\admin\index.html", line 1, in top-level template code
    {% extends 'admin/master.html' %}
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\templates\bootstrap2\admin\master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\templates\bootstrap2\admin\base.html", line 35, in top-level template code
    {% block page_body %}
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\templates\bootstrap2\admin\base.html", line 42, in block "page_body"
    {% block main_menu %}
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\templates\bootstrap2\admin\base.html", line 44, in block "main_menu"
    {{ layout.menu() }}
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\jinja2\runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\templates\bootstrap2\admin\layout.html", line 55, in template
    {%- if item.is_accessible() and item.is_visible() -%}
  File "c:\users\sergio\desktop\project\venv\lib\site-packages\flask_admin\menu.py", line 126, in is_accessible
    return self._view.is_accessible()
  File "C:\Users\Sergio\Desktop\heroku deploy\Team-668\app\models.py", line 378, in is_accessible
    admin = User.query.filter(email=current_app.config["ADMIN_MAIL"])
TypeError: filter() got an unexpected keyword argument 'email'
2020-10-09 15:33:31,712 INFO: HomeShop startup [in C:\Users\Sergio\Desktop\heroku deploy\Team-668\app\__init__.py:110]
